# Travis YAML based on idea at
# https://therenegadecoder.com/code/how-to-build-latex-with-travis-ci-and-minted/

language: generic
sudo: required
before_install:
#
install:
  - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
before_script:
  # Change working directory so including files will work
  - cd $TRAVIS_BUILD_DIR/tests/article/
script:
  - texliveonfly --compiler=pdflatex ./instructions-EN.tex
  - texliveonfly --compiler=pdflatex ./instructions-EN.tex
  - texliveonfly --compiler=pdflatex ./instructions-EN.tex
  - bibtex ./instructions-EN
  - texliveonfly --compiler=pdflatex ./instructions-EN.tex
  - texliveonfly --compiler=pdflatex ./instructions-EN.tex
notifications:
  email: false
